# Generated by Django 2.2.8 on 2020-01-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200114_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
